//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirPlan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class logService
    {
        public int id { get; set; }
        public string log { get; set; }
        public System.DateTime date { get; set; }
        public string state { get; set; }
        public int idUser { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
