//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirPlan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackUser
    {
        public int id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> Login { get; set; }
        public Nullable<System.DateTime> Out { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
